travis:
  secure:
    BINSTAR_TOKEN: rriRjPHnugdC8aj03xJhRYYF1BzKOj19ypb5nekKCtuYDB5M/dByeZ4Vg06uZO7y8QwQ9AeroEdacu9jsFyPdCp+QUPC1G0qS334Q08SJ6N4FUHKIvzVPaSgOeSmvudsxBPumTOfuhvyKBuw1y3OqSpIoOW5LTs8ezBXXfc1FM0d8qA9e0thFcRHOQ4AP+s0/4kkLECQ1MbVf5pN45Oqwjn4HRd5PvpWERfh/wh/m25rI2Lffh4qQM4o1ijAqeIhv34tUqMDXWHYBBFqjxPdRTW4J28DZaDk5U+xhp16CPnOdIsRvkj5BRTChO8ktdx1HmSfWl2eg82tRI4ssNQo9UePsAXAbGK6ySF7kyU8KR36mi9yl/fNiRmTLA3AP4msVeVVSwLmirYeBZdL3YL4+0DV8coGaSqJC9ZtSC7E5AhRWDSA2uzcL+JN03o6dvV4ewuj5dyqHRq6bNKADjqq7+a2tC1fvBqMC5qDD+psd8mJePRVXTIDsTxctAXufPNVIMnfNx3eS07nwG7Albr7sWwSWEKlon/9kFftXrQr3myv/If7ztmazcAEUFzUvgHthjmHTUUshjDUq2EwrsFth1Y6y6wBsl04X0+fGrMbOOyR4XPaBx16UNNNpU7p6sbFk+nfg3zUFq7LizsMlOE1NiyOF5FIrx2kjDIfTkBKQAg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
